# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Foreword 2016

description: Foreword 2016:/ Seattle Pacific University Visual Communications Senior Show

url: "http://localhost:4000" # dev
baseurl: "" # dev

# url: "http://www.loganpendergrass.com" # test
# baseurl: "/viscom2016" # test

# Build settings
markdown: kramdown


# Ruby shit
gems:
  - octopress-autoprefixer